name: 💡 Suggestion / Feedback
description: Share an idea to improve the catalog, UI/UX, or metadata schema.
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see improved or added?
      placeholder: Briefly describe your suggestion.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide more context, examples, or references.
  - type: input
    id: links
    attributes:
      label: Relevant links (optional)
      placeholder: e.g., paper links, dataset URLs, screenshots
  - type: checkboxes
    id: willing
    attributes:
      label: Are you willing to help implement this?
      options:
        - label: Yes, I can help implement or test
